---
- name: Update and upgrade
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    upgrade: "dist"
    autoremove: true
    autoclean: true

- name: Check if a reboot is required
  ansible.builtin.stat:
  path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the system if necessary
  ansible.builtin.reboot:
  reboot_timeout: 600
  when: reboot_required.stat.exists

