- name: Install OpenSSH Server
  ansible.builtin.apt:
    name: openssh-server
    state: present
    update_cache: yes

- name: Configure SSHD Config to Disable Root Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify:
    - Restart SSH

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - Restart SSH

- name: Disable login for users with empty passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify:
    - Restart SSH

- name: Configure SSH to Allow Only Specific Users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers'
    line: 'AllowUsers ubuntu'
  notify:
    - Restart SSH

- name: Ensure SSH service is running and enabled
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: yes


