---
- name: Ensure docker-compose is installed
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Jellyfin directory
  ansible.builtin.file:
    path: /home/ubuntu/docker-compose/jellyfin
    state: directory
    mode: '0755'
    owner: ubuntu  
    group: ubuntu

- name: Deploy Jellyfin using Docker Compose
  ansible.builtin.template:
    src: "templates/docker_compose.yaml.j2"
    dest: "/home/ubuntu/docker-compose/jellyfin/docker-compose.yaml"
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  notify:
    - Start Jellyfin

- name: Run Jellyfin docker-compose up
  community.docker.docker_compose:
    project_src: /home/ubuntu/docker-compose/jellyfin
    state: present