- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set incoming rules
  community.general.ufw:
    default: deny
    direction: incoming
    state: enabled

- name: Set outgoing rules
  community.general.ufw:
    default: allow
    direction: outgoing
    state: enabled

- name: Allow SSH connections
  community.general.ufw:
    rule: limit
    port: '22'
    state: enabled

- name: Allow HTTP traffic
  community.general.ufw:
    rule: allow
    port: '80'
    state: enabled

- name: Allow HTTPS traffic
  community.general.ufw:
    rule: allow
    port: '443'
    state: enabled
