---
- name: Server deployment
  hosts: servers
  become: true
  roles:
    - set_passwd
    - configure_firewall
    - configure_ssh
    - docker_install
    - portainer_deploy

  # ansible-playbook -i inventory.yml playbook.yml --ask-vault-pass
